name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Check formatting
        run: black --check src tests
      - name: Lint
        run: flake8 src tests
      - name: Type check
        run: mypy src
      - name: Run tests
        run: pytest -q

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install -e .
      - name: Build distributions
        run: |
          rm -rf dist build
          python -m build
      - name: Validate metadata
        run: twine check dist/*
